#!/bin/bash
# Simple test de stress TCPSYN con nping del paquete https://nmap.org/nping
# (C) hackingyseguridad.com 2017
# Uso: ./tcpsyn IP puerto_TCP

echo Uso: ./tcpsyn IP puertoTCP
OIFS=$IFS;
IFS=$'\n';
nping $1 -p $2 --tcp-connect -ttl 255 --rate=3 -c 999999999
